name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-build.txt) { pip install -r requirements-build.txt }
          pip show pyinstaller

      - name: Build (PyInstaller)
        env:
          QT_MODULE: PySide6
        run: |
          pyinstaller --clean --noconfirm main.spec
          echo "Built files:"
          Get-ChildItem -Recurse dist

      - name: Archive artifacts
        run: |
          cd dist
          7z a streamrip-gui-windows.zip streamrip-gui\*
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/streamrip-gui-windows.zip

  release-source:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Attach source archives
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            # GitHub auto-provides source tar/zip, but if you want to attach custom zips:
            # (usually not necessary; you can skip this job entirely)
