name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout (no extra tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-build.txt) { pip install -r requirements-build.txt }
          pip install pyinstaller
          pip show pyinstaller

      - name: Build (PyInstaller via main.spec)
        shell: pwsh
        env:
          QT_MODULE: PySide6
        run: |
          pyinstaller --clean --noconfirm main.spec
          if (-not (Test-Path "dist\streamrip-gui\streamrip-gui.exe")) {
            Write-Error "EXE not found after build."
          }

      - name: Publish GitHub Release (attach .exe)
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/streamrip-gui/streamrip-gui.exe
